In [4]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Larger test size
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=1
)

# ===============================
# KNN USING LIBRARY
# ===============================
knn_lib = KNeighborsClassifier(n_neighbors=1)
knn_lib.fit(X_train, y_train)

y_pred_lib = knn_lib.predict(X_test)

# Accuracy in percentage
acc_lib = accuracy_score(y_test, y_pred_lib) * 100

# Confusion Matrix (Library)
cm_lib = confusion_matrix(y_test, y_pred_lib)

# ===============================
# KNN WITHOUT LIBRARY
# ===============================
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

def knn_manual(X_train, y_train, x_test, k):
    distances = []
    for i in range(len(X_train)):
        dist = euclidean_distance(X_train[i], x_test)
        distances.append((dist, y_train[i]))
    distances.sort(key=lambda x: x[0])
    k_nearest = distances[:k]
    labels = [label for _, label in k_nearest]
    return max(set(labels), key=labels.count)

k = 1
y_pred_manual = np.array([knn_manual(X_train, y_train, x, k) for x in X_test])

# Accuracy in percentage
acc_manual = (np.sum(y_pred_manual == y_test) / len(y_test)) * 100

# Confusion Matrix (Manual)
cm_manual = confusion_matrix(y_test, y_pred_manual)

# ===============================
# RESULT TABLE
# ===============================
result_table = pd.DataFrame({
    "Actual": y_test,
    "Predicted (Library)": y_pred_lib,
    "Predicted (Manual)": y_pred_manual
})

# ===============================
# OUTPUT
# ===============================
print("Accuracy using library KNN: {:.2f}%".format(acc_lib))
print("Confusion Matrix (Library KNN):\n", cm_lib)

print("\nAccuracy without library KNN: {:.2f}%".format(acc_manual))
print("Confusion Matrix (Manual KNN):\n", cm_manual)

print("\nResult Table (first 5 rows):")
print(result_table.head())





Accuracy using library KNN: 96.67%
Confusion Matrix (Library KNN):
 [[19  0  0]
 [ 0 20  1]
 [ 0  1 19]]

Accuracy without library KNN: 96.67%
Confusion Matrix (Manual KNN):
 [[19  0  0]
 [ 0 20  1]
 [ 0  1 19]]

Result Table (first 5 rows):
   Actual  Predicted (Library)  Predicted (Manual)
0       0                    0                   0
1       1                    1                   1
2       1                    1                   1
3       0                    0                   0
4       2                    2                   2
